name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Sync to S3
      uses: aws-actions/s3-sync-action@v1.1.2
      with:
        aws-region: 'us-west-2'
        source-dir: 'build'
        destination-bucket: ${{ secrets.AWS_S3_BUCKET }}
